# Generated by Django 4.0.4 on 2022-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_address',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
