# Generated by Django 4.0.4 on 2022-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_address_city_doctor_hospital_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('current_role', models.CharField(max_length=1000)),
                ('ultimate_goal', models.CharField(max_length=1000)),
                ('biggest_achievement', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('product_price', models.CharField(max_length=1000)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_category', models.CharField(max_length=1000)),
                ('product_subcategory', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='people',
            new_name='ouruser',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_address',
            field=models.CharField(max_length=1000),
        ),
    ]
