# Generated by Django 4.0.4 on 2022-06-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_people_delete_ouruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='User_name',
        ),
    ]
