# Generated by Django 4.0.4 on 2022-06-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_address_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='author',
        ),
        migrations.AddField(
            model_name='address',
            name='people',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AddField(
            model_name='bio',
            name='people',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='people',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
    ]
