# Generated by Django 4.0.4 on 2022-06-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_address_people_address_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
    ]
