# Generated by Django 4.0.4 on 2022-06-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_address_people_alter_bio_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='people',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='current_role',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='ultimate_goal',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='people',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='people',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
        migrations.AddField(
            model_name='address',
            name='street_number_and_name',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AddField(
            model_name='bio',
            name='date_of_birth',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='bio',
            name='hobbies',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='blood_pressure',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='disabilities',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sugar_level',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='contact',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bio',
            name='biggest_achievement',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bio',
            name='people',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=220),
        ),
    ]
